Change of import of libraries.
Tried to fix issue displayed below.

[root@alarm BeagleDash]# python3.3 CANtoUDP.py
Traceback (most recent call last):
File "CANtoUDP.py", line 10, in <module>
listeners = [csv, UDPSender()]
TypeError: 'module' object is not callable
Exception AttributeError: "'super' object has no attribute '__del__'" in
<bound method CSVWriter.__del__ of <can.CAN.CSVWriter object at
0xb6867730>> ignored